version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  assets.api:
    image: ${DOCKER_REGISTRY-}assetsapi
    environment:
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 50000:80
    depends_on:
      - sqlserver
    build:
      context: .
      dockerfile: Assets.API/Dockerfile

  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    environment:
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 50001:80
    depends_on:
      - sqlserver
    build:
      context: .
      dockerfile: Users.API/Dockerfile

  transactions.api:
    image: ${DOCKER_REGISTRY-}transactionsapi
    environment:
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 50002:80
    depends_on:
      - sqlserver
    build:
      context: .
      dockerfile: Transactions.API/Dockerfile