version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA="Y"
    ports:
      - 1450:1433

  assets.api:
    image: ${DOCKER_REGISTRY-}assetsapi
    environment:
      - ADMIN_GUID_PASSWORD=${ADMIN_GUID_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - 50000:80
    depends_on:
      - sqlserver
    build:
      context: .
      dockerfile: Assets.API/Dockerfile

  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    environment:
      - ADMIN_GUID_PASSWORD=${ADMIN_GUID_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - 50001:80
    depends_on:
      - sqlserver
    build:
      context: .
      dockerfile: Users.API/Dockerfile

  transactions.api:
    image: ${DOCKER_REGISTRY-}transactionsapi
    environment:
      - ADMIN_GUID_PASSWORD=${ADMIN_GUID_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - 50002:80
    depends_on:
      - sqlserver
    build:
      context: .
      dockerfile: Transactions.API/Dockerfile